version: 2.1
jobs:
  build:
    working_directory: ~/NexusPreTest
    machine:
      # image: circleci/node:10.16.3
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: update-apt
          command: sudo apt-get update
      - run:
          name: install-curl
          command: sudo apt-get install curl --allow-unauthenticated
      - run:
          name: install-nodejs
          command: 'curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -'
      - run:
          name: install-update-node-npm
          command: 'sudo apt-get install nodejs && sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: run-selenoid
          command: docker-compose -f selenoid/docker-compose.yml up -d
      - run:
          name: test
          command: npm run test-docker-chrome
    #   - run:
    #       name: code-coverage
    #       command: './node_modules/.bin/nyc report --reporter=text-lcov'
    #   - store_artifacts:
    #       path: test-results.xml
    #       prefix: tests
    #   - store_artifacts:
    #       path: coverage
    #       prefix: coverage
    #   - store_test_results:
    #       path: test-results.xml