version: 2.1
jobs:
  build:
    working_directory: ~/NexusPreTest
    docker:
      - image: circleci/node:10.16.3
      - image: selenoid/vnc_chrome:68.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: curl-docker-compose
          command: sudo curl -L --fail https://github.com/docker/compose/releases/download/1.24.0/run.sh -o /usr/local/bin/docker-compose
      - run:
          name: chmod-docker-compose
          command: sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: run-selenoid
          command: cd selenoid && docker-compose up -d
      - run:
          name: test
          command: cd .. && npm run test-docker-chrome
    #   - run:
    #       name: code-coverage
    #       command: './node_modules/.bin/nyc report --reporter=text-lcov'
    #   - store_artifacts:
    #       path: test-results.xml
    #       prefix: tests
    #   - store_artifacts:
    #       path: coverage
    #       prefix: coverage
    #   - store_test_results:
    #       path: test-results.xml